"""Python-owned conditional string-reversal research lab."""

from .analysis import (
    PairedEffect,
    PcaAccumulator,
    PcaResult,
    SelectorTarget,
    SteeringSpec,
    compare_paired_conditions,
    fit_pca,
    make_selector_steering,
    paired_effect,
    project_rows,
    steering_specs_for_variant,
)
from .config import (
    AnalysisConfig,
    ExperimentConfig,
    ModelConfig,
    Profile,
    TrainingConfig,
    Variant,
    make_profile,
)
from .data import (
    Batch,
    EncodedExample,
    TokenCodec,
    encode_example,
    iter_batches,
    make_batch,
)
from .programs import (
    CoefficientInitialization,
    ProgramInputLayout,
    ProgramInputSource,
    ProgramSpec,
    SparseMultilinearMap,
    build_program_spec,
    f_coefficient_index,
    iter_f_coefficient_indices,
    iter_p_coefficient_indices,
    make_f_reference_map,
    make_p_reference_map,
    output_major_flat_index,
    p_coefficient_index,
    sequence_coordinate,
)

from .protocol import (
    Evaluation,
    Example,
    ProtocolConfig,
    SplitSizes,
    evaluate,
    generate_disjoint_splits,
    predict_copy,
    predict_oracle,
    predict_reverse,
)


__all__ = [
    "AnalysisConfig",
    "Batch",
    "CoefficientInitialization",
    "EncodedExample",
    "Evaluation",
    "Example",
    "ExperimentConfig",
    "ModelConfig",
    "PairedEffect",
    "PcaAccumulator",
    "PcaResult",
    "Profile",
    "ProgramInputLayout",
    "ProgramInputSource",
    "ProgramSpec",
    "ProtocolConfig",
    "SelectorTarget",
    "SparseMultilinearMap",
    "SplitSizes",
    "SteeringSpec",
    "TokenCodec",
    "TrainingConfig",
    "Variant",
    "build_program_spec",
    "compare_paired_conditions",
    "encode_example",
    "evaluate",
    "f_coefficient_index",
    "fit_pca",
    "generate_disjoint_splits",
    "iter_batches",
    "iter_f_coefficient_indices",
    "iter_p_coefficient_indices",
    "make_batch",
    "make_f_reference_map",
    "make_p_reference_map",
    "make_profile",
    "make_selector_steering",
    "output_major_flat_index",
    "p_coefficient_index",
    "paired_effect",
    "predict_copy",
    "predict_oracle",
    "predict_reverse",
    "project_rows",
    "sequence_coordinate",
    "steering_specs_for_variant",
]
