"""Dependency-free model interchange formats and architecture adapters."""

from .contracts import (
    MAXIMUM_DECODER_BLOCKS,
    MAXIMUM_TENSOR_ELEMENTS,
    Float32Tensor,
    build_bundle_from_tensors,
    bundle_tensors,
    current_decoder_parameter_specs,
)
from .conversion import (
    EXPORT_FORMATS,
    IMPORT_FORMATS,
    convert_model,
    export_model,
    load_model,
)
from .gguf import (
    GGML_TYPE_F32,
    GGUF_VERSION,
    GGUFInspection,
    GGUFTensorInfo,
    RIFTCO_GGUF_ARCHITECTURE,
    UnsupportedGGUFError,
    export_gguf,
    inspect_gguf,
    load_gguf,
)
from .huggingface import (
    CONFIG_NAME as HUGGINGFACE_CONFIG_NAME,
    HUGGINGFACE_ARCHITECTURE_CLASS,
    HUGGINGFACE_MODEL_TYPE,
    MAXIMUM_JSON_BYTES as HUGGINGFACE_MAXIMUM_JSON_BYTES,
    RIFTCO_ARCHITECTURE,
    RIFTCO_INTERCHANGE_VERSION,
    TOKENIZER_CONFIG_NAME as HUGGINGFACE_TOKENIZER_CONFIG_NAME,
    TOKENIZER_NAME as HUGGINGFACE_TOKENIZER_NAME,
    WEIGHTS_NAME as HUGGINGFACE_WEIGHTS_NAME,
    UnsupportedHuggingFaceModelError,
    export_huggingface_directory,
    huggingface_parameter_map,
    import_huggingface_directory,
    load_huggingface_directory,
)
from .safetensors import (
    MAXIMUM_HEADER_BYTES as SAFETENSORS_MAXIMUM_HEADER_BYTES,
    MAXIMUM_TENSOR_COUNT as SAFETENSORS_MAXIMUM_TENSOR_COUNT,
    SAFETENSORS_DTYPE_F32,
    SAFETENSORS_METADATA_KEY,
    SafeTensorsFile,
    decode_safetensors,
    encode_safetensors,
    load_safetensors,
    save_safetensors,
)
from .onnx import (
    MAXIMUM_ONNX_FILE_BYTES,
    MAXIMUM_ONNX_INITIALIZERS,
    MAXIMUM_ONNX_NODES,
    MAXIMUM_ONNX_PROTOBUF_FIELDS,
    MAXIMUM_ONNX_SIDECAR_BYTES,
    ONNX_CANONICAL_GRAPH_FORMAT,
    ONNX_CANONICAL_GRAPH_VERSION,
    ONNX_INPUT_CONTRACT,
    ONNX_IR_VERSION,
    ONNX_OPSET_VERSION,
    ONNX_PRODUCER_VERSION,
    ONNX_SIDECAR_FORMAT,
    ONNX_SIDECAR_SUFFIX,
    ONNX_SIDECAR_VERSION,
    ONNXInspection,
    ONNXNodeInfo,
    ONNXTensorInfo,
    ONNXValueInfo,
    UnsupportedONNXImportError,
    export_onnx,
    inspect_onnx,
    load_onnx,
    onnx_sidecar_path,
)


__all__ = [
    "EXPORT_FORMATS",
    "GGML_TYPE_F32",
    "GGUF_VERSION",
    "GGUFInspection",
    "GGUFTensorInfo",
    "HUGGINGFACE_ARCHITECTURE_CLASS",
    "HUGGINGFACE_CONFIG_NAME",
    "HUGGINGFACE_MAXIMUM_JSON_BYTES",
    "HUGGINGFACE_MODEL_TYPE",
    "HUGGINGFACE_TOKENIZER_CONFIG_NAME",
    "HUGGINGFACE_TOKENIZER_NAME",
    "HUGGINGFACE_WEIGHTS_NAME",
    "IMPORT_FORMATS",
    "MAXIMUM_DECODER_BLOCKS",
    "MAXIMUM_ONNX_FILE_BYTES",
    "MAXIMUM_ONNX_INITIALIZERS",
    "MAXIMUM_ONNX_NODES",
    "MAXIMUM_ONNX_PROTOBUF_FIELDS",
    "MAXIMUM_ONNX_SIDECAR_BYTES",
    "MAXIMUM_TENSOR_ELEMENTS",
    "ONNX_CANONICAL_GRAPH_FORMAT",
    "ONNX_CANONICAL_GRAPH_VERSION",
    "ONNX_INPUT_CONTRACT",
    "ONNX_IR_VERSION",
    "ONNX_OPSET_VERSION",
    "ONNX_PRODUCER_VERSION",
    "ONNX_SIDECAR_FORMAT",
    "ONNX_SIDECAR_SUFFIX",
    "ONNX_SIDECAR_VERSION",
    "ONNXInspection",
    "ONNXNodeInfo",
    "ONNXTensorInfo",
    "ONNXValueInfo",
    "RIFTCO_ARCHITECTURE",
    "RIFTCO_GGUF_ARCHITECTURE",
    "RIFTCO_INTERCHANGE_VERSION",
    "SAFETENSORS_DTYPE_F32",
    "SAFETENSORS_MAXIMUM_HEADER_BYTES",
    "SAFETENSORS_MAXIMUM_TENSOR_COUNT",
    "SAFETENSORS_METADATA_KEY",
    "Float32Tensor",
    "SafeTensorsFile",
    "UnsupportedGGUFError",
    "UnsupportedHuggingFaceModelError",
    "UnsupportedONNXImportError",
    "build_bundle_from_tensors",
    "bundle_tensors",
    "current_decoder_parameter_specs",
    "convert_model",
    "decode_safetensors",
    "encode_safetensors",
    "export_gguf",
    "export_huggingface_directory",
    "export_model",
    "export_onnx",
    "huggingface_parameter_map",
    "import_huggingface_directory",
    "inspect_gguf",
    "inspect_onnx",
    "load_gguf",
    "load_huggingface_directory",
    "load_model",
    "load_onnx",
    "onnx_sidecar_path",
    "load_safetensors",
    "save_safetensors",
]
