"""Dependency-free HTTP adapter for the in-process model service."""

from __future__ import annotations

from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import ipaddress
import json
import os
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from ..artifacts import ModelBundle
from .chat_ui import CHAT_HTML
from .service import ModelService, ServingConfig


class ModelHTTPServer(ThreadingHTTPServer):
    """Local JSON adapter that owns and closes one ModelService."""

    daemon_threads = True
    allow_reuse_address = True

    def __init__(
        self,
        server_address: tuple[str, int],
        service: ModelService,
    ) -> None:
        self.model_service = service
        self.enforce_loopback_host = _is_loopback_name(server_address[0])
        super().__init__(server_address, _GenerationRequestHandler)

    def server_close(self) -> None:
        try:
            super().server_close()
        finally:
            self.model_service.close()


class _GenerationRequestHandler(BaseHTTPRequestHandler):
    server: ModelHTTPServer
    protocol_version = "HTTP/1.1"

    def do_GET(self) -> None:
        if not self._accept_request_host():
            return
        if self.path in {"/", "/chat"}:
            self._send_bytes(
                HTTPStatus.OK,
                "text/html; charset=utf-8",
                CHAT_HTML,
            )
            return
        if self.path not in {"/health", "/v1/health"}:
            self._send_error(
                HTTPStatus.NOT_FOUND,
                "route not found",
            )
            return
        self._send_json(HTTPStatus.OK, self.server.model_service.health())

    def do_POST(self) -> None:
        if not self._accept_request_host():
            return
        if self.path != "/v1/generate":
            self._send_error(
                HTTPStatus.NOT_FOUND,
                "route not found",
            )
            return
        if self.headers.get_content_type() != "application/json":
            self._send_error(
                HTTPStatus.UNSUPPORTED_MEDIA_TYPE,
                "Content-Type must be application/json",
            )
            return
        try:
            request = self._read_json_object()
            allowed = {
                "prompt",
                "max_new_tokens",
                "temperature",
                "top_k",
                "seed",
            }
            unknown = sorted(set(request) - allowed)
            if unknown:
                raise ValueError(
                    "unknown request fields: " + ", ".join(unknown)
                )
            if "prompt" not in request:
                raise ValueError("request requires prompt")
            prompt = request["prompt"]
            if not isinstance(prompt, str):
                raise TypeError("prompt must be a string")
            result = self.server.model_service.generate(
                prompt,
                max_new_tokens=request.get("max_new_tokens", 32),
                temperature=request.get("temperature", 0.0),
                top_k=request.get("top_k"),
                seed=request.get("seed", 0),
            )
            prompt_bytes = prompt.encode("utf-8")
            if not result.raw_bytes.startswith(prompt_bytes):
                raise RuntimeError(
                    "generated bytes do not preserve the prompt prefix"
                )
            generated_text = result.raw_bytes[
                len(prompt_bytes) :
            ].decode("utf-8", errors="replace")
            self._send_json(
                HTTPStatus.OK,
                {
                    "artifact_id": self.server.model_service.artifact_id,
                    "prompt": prompt,
                    "text": result.text,
                    "generated_text": generated_text,
                    "prompt_token_ids": list(result.prompt_token_ids),
                    "generated_token_ids": list(
                        result.generated_token_ids
                    ),
                    "token_ids": list(result.token_ids),
                },
            )
        except (TypeError, ValueError, json.JSONDecodeError) as error:
            self._send_error(HTTPStatus.BAD_REQUEST, str(error))
        except Exception:
            self._send_error(
                HTTPStatus.INTERNAL_SERVER_ERROR,
                "generation failed",
            )

    def _read_json_object(self) -> dict[str, Any]:
        raw_length = self.headers.get("Content-Length")
        if raw_length is None:
            raise ValueError("Content-Length is required")
        try:
            length = int(raw_length, 10)
        except ValueError as error:
            raise ValueError("Content-Length must be an integer") from error
        if length <= 0:
            raise ValueError("request body must not be empty")
        maximum = self.server.model_service.config.maximum_request_bytes
        if length > maximum:
            raise ValueError(
                f"request body exceeds the {maximum}-byte limit"
            )
        payload = self.rfile.read(length)
        if len(payload) != length:
            raise ValueError("request body ended before Content-Length")
        value = json.loads(payload.decode("utf-8", errors="strict"))
        if not isinstance(value, dict):
            raise ValueError("request JSON must be an object")
        return value

    def _accept_request_host(self) -> bool:
        if (
            self.server.enforce_loopback_host
            and not _is_loopback_host_header(self.headers.get("Host"))
        ):
            self._send_error(
                HTTPStatus.MISDIRECTED_REQUEST,
                "loopback server requires a loopback Host header",
            )
            return False
        return True

    def _send_error(self, status: HTTPStatus, detail: str) -> None:
        self._send_json(
            status,
            {
                "error": status.phrase,
                "detail": detail,
            },
        )

    def _send_json(
        self,
        status: HTTPStatus,
        value: object,
    ) -> None:
        body = json.dumps(
            value,
            ensure_ascii=False,
            allow_nan=False,
            separators=(",", ":"),
        ).encode("utf-8")
        self._send_bytes(
            status,
            "application/json; charset=utf-8",
            body,
        )

    def _send_bytes(
        self,
        status: HTTPStatus,
        content_type: str,
        body: bytes,
    ) -> None:
        self.send_response(int(status))
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header(
            "Content-Security-Policy",
            "default-src 'none'; "
            "connect-src 'self'; "
            "style-src 'unsafe-inline'; "
            "script-src 'unsafe-inline'; "
            "base-uri 'none'; "
            "form-action 'self'; "
            "frame-ancestors 'none'",
        )
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("X-Frame-Options", "DENY")
        self.send_header("Connection", "close")
        self.end_headers()
        self.wfile.write(body)
        self.close_connection = True

    def log_message(self, _format: str, *args: object) -> None:
        del args


def create_http_server(
    bundle: ModelBundle | str | os.PathLike[str],
    *,
    host: str = "127.0.0.1",
    port: int = 8000,
    config: ServingConfig | None = None,
) -> ModelHTTPServer:
    """Create, but do not start, a local generation HTTP server."""

    if not isinstance(host, str) or not host:
        raise ValueError("host must be a nonempty string")
    checked_port = _nonnegative_integer(port, "port")
    if checked_port > 65535:
        raise ValueError("port must be at most 65535")
    loaded = (
        ModelBundle.load(Path(bundle))
        if isinstance(bundle, (str, os.PathLike))
        else bundle
    )
    service = ModelService(loaded, config)
    try:
        return ModelHTTPServer((host, checked_port), service)
    except BaseException:
        service.close()
        raise


def serve_model(
    bundle: ModelBundle | str | os.PathLike[str],
    *,
    host: str = "127.0.0.1",
    port: int = 8000,
    config: ServingConfig | None = None,
) -> None:
    """Run the local HTTP adapter until interrupted."""

    server = create_http_server(
        bundle,
        host=host,
        port=port,
        config=config,
    )
    try:
        server.serve_forever()
    finally:
        server.server_close()


def _nonnegative_integer(value: object, name: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{name} must be an int")
    if value < 0:
        raise ValueError(f"{name} must not be negative")
    return value


def _is_loopback_host_header(value: str | None) -> bool:
    if value is None or not value.strip():
        return False
    try:
        parsed = urlsplit(f"//{value.strip()}")
        hostname = parsed.hostname
        parsed.port
    except ValueError:
        return False
    if (
        hostname is None
        or parsed.username is not None
        or parsed.password is not None
    ):
        return False
    return _is_loopback_name(hostname)


def _is_loopback_name(value: str) -> bool:
    normalized = value.lower().rstrip(".")
    if normalized == "localhost":
        return True
    try:
        return ipaddress.ip_address(normalized).is_loopback
    except ValueError:
        return False


__all__ = [
    "ModelHTTPServer",
    "create_http_server",
    "serve_model",
]
